version: "3.9"
services:
  api:
    build: ./api
    environment:
      APP_ENV: ${APP_ENV:-prod}
      API_BEARER_TOKEN: ${API_BEARER_TOKEN}
      UNIFI_BASE: ${UNIFI_BASE}
      UNIFI_SITE: ${UNIFI_SITE:-default}
      UNIFI_VERSION: ${UNIFI_VERSION:-9.0.0}
      UNIFI_USER: ${UNIFI_USER}
      UNIFI_PASS: ${UNIFI_PASS}
      UNIFI_VERIFY_SSL: ${UNIFI_VERIFY_SSL:-true}
    networks:
      - neuralnoc
      # - sharednet
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./api/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./api/public:/var/www/public:ro
    ports:
      - "8181:80"
    depends_on:
      - api
    networks:
      - neuralnoc
      # - sharednet
    restart: unless-stopped

networks:
  neuralnoc:
    external: true
  # sharednet:
  #   driver: bridge


